const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');


const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
      license: {
        name: "Apache 2.0"
      },
      contact: {
        name: "Developer Garret",
        email: "garret456963@gmail.com"
      }


    },
    host: "localhost:3000",
    basePath: "/",
    schemes:"http"

  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['restfulAPI.js'],
};

const specs = swaggerJsdoc(options);
module.exports = (app) => {
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
}

